const $=id=>document.getElementById(id);
const STAGES=["preflight","agent_security","agent_supervisor","membership_boundary_tests","specialist_security_tests","former_probe","fetch_agent","repair_queue","incremental_coverage_before_repair","partial_history_ranges","recovery_scheduler","case_manager","evidence_vault","corporate_identity_resolver","secondary_source_probe","ticker_rename_probe","specialist_former_tickers","specialist_corporate_actions","specialist_data_sources","specialist_bottlenecks","agent_deliberation","alias_audit_materialization","incremental_coverage_after_aliases","universe_audit","jarvis_security_tests","jarvis_supervisor","jarvis_audit_log_start","jarvis_audit","jarvis_audit_log_complete","watchdog_pre_experiments","vision_multi_strategy","vision_cross_sectional","ultron_adversarial","edith_record","gatekeeper","optimizer_summary"];
const roles=[
["Controller",["agent_security","agent_supervisor","membership_boundary_tests","specialist_security_tests","former_probe","repair_queue","secondary_source_probe","ticker_rename_probe","alias_audit_materialization","universe_audit","optimizer_summary"],"⌘"],
["FETCH",["fetch_agent"],"F"],["ARCHIVIST",["specialist_former_tickers"],"↺"],["ORACLE",["specialist_corporate_actions"],"⇄"],["CIPHER",["specialist_data_sources"],"◉"],["PULSE",["specialist_bottlenecks","agent_deliberation"],"⌁"],["WATCHDOG",["watchdog_pre_experiments"],"◈"],["GATEKEEPER",["gatekeeper"],"⚿"],["JARVIS",["jarvis_security_tests","jarvis_supervisor","jarvis_audit_log_start","jarvis_audit","jarvis_audit_log_complete"],"J"],["VISION",["vision_multi_strategy","vision_cross_sectional"],"V"],["ULTRON",["ultron_adversarial"],"U"],["EDITH",["edith_record"],"E"]];
function pct(n){return Math.max(0,Math.min(100,n||0))}
function esc(v){return String(v??"").replace(/[&<>"\']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","\'":"&#39;"}[ch]))}
function fmt(s){s=Math.max(0,Math.floor(s||0));return s<60?s+"s":Math.floor(s/60)+"m "+s%60+"s"}
function audit(o){let lines=(o||"").split("\n").filter(x=>x.includes("B27B_UNIVERSE_AUDIT")),line=lines.at(-1)||"",a=line.match(/(?:^|\s)coverage=(\d+(?:\.\d+)?)/),f=line.match(/(?:^|\s)former_coverage=(\d+(?:\.\d+)?)/);return{overall:a?+a[1]*100:null,former:f?+f[1]*100:null}}
function roleState(cp,keys,active){if(active&&keys.includes(active))return{label:"ACTIVE",cls:"running",detail:active.replaceAll("_"," ")};let found=keys.map(k=>[k,cp[k]]).filter(x=>x[1]);let failed=[...found].reverse().find(x=>x[1].status==="failed");if(failed)return{label:"BLOCKED",cls:"failed",detail:failed[0].replaceAll("_"," ")};if(found.length&&found.every(x=>x[1].status==="complete"))return{label:"COMPLETE",cls:"status",detail:found.at(-1)[0].replaceAll("_"," ")};return{label:"STANDBY",cls:"muted",detail:"queued / dependency not reached"}}
const GROUPS=[["SECURITY",0,5],["DATA",5,16],["SPECIALISTS",16,21],["AUDIT",21,30],["EXPERIMENTS",30,33],["REVIEW",33,36]];
const VALIDATION=["preflight","agent_security","agent_supervisor","membership_boundary_tests","specialist_security_tests","universe_audit","jarvis_security_tests","jarvis_supervisor","watchdog_pre_experiments","gatekeeper"];
function stageState(name,v,active){if(name===active)return["ACTIVE","running"];if(!v)return["QUEUED","muted"];if(v.status==="complete")return["COMPLETE","status"];if(v.status==="failed")return["FAILED","failed"];return[String(v.status||"QUEUED").toUpperCase(),"muted"]}
async function tick(){try{
let r=await fetch("/api/status?ts="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error("status "+r.status);let d=await r.json(),cp=(d.checkpoint||{}).stages||{},done=STAGES.filter(x=>cp[x]&&cp[x].status==="complete").length,activeIndex=d.active_stage?STAGES.indexOf(d.active_stage):-1,p=Math.round(done/STAGES.length*100),elapsed=d.stage_started_at?Date.now()/1000-d.stage_started_at:0;
$("system").textContent=d.status==="failed"?"RESEARCH BLOCKED":d.status==="complete"?"PIPELINE COMPLETE":"RESEARCH ACTIVE";
$("sub").textContent=d.error||(d.active_stage?"NOW WORKING: "+d.active_stage.replaceAll("_"," ").toUpperCase()+" • "+fmt(elapsed):"Controller ready / evaluating checkpoint");
$("progress").textContent=p+"%";$("stageCount").textContent=done+" / "+STAGES.length+" COMPLETE";
let completedValidation=VALIDATION.filter(x=>cp[x]&&cp[x].status==="complete").length;$("validationReady").textContent=completedValidation+" / "+VALIDATION.length+" PASSED";
let cv=audit(d.output),dataRead=(cv.overall!=null&&cv.former!=null)?Math.min(cv.overall,cv.former):null;$("dataReady").textContent=dataRead==null?"—":dataRead.toFixed(1)+"%";
let failed=STAGES.find(x=>cp[x]&&cp[x].status==="failed"),blocker=failed||((cv.former!=null&&cv.former<90)?"former_coverage":(cv.overall!=null&&cv.overall<90)?"overall_coverage":null);
let engineState=d.active_stage?"RUNNING":d.status==="complete"?"COMPLETE":d.status==="failed"?"BLOCKED — DATA GATE":"IDLE / READY",engineCls=d.active_stage?"stateRunning":d.status==="complete"?"stateComplete":d.status==="failed"?"stateBlocked":"stateIdle";$("engineState").textContent=engineState;$("engineStatusBar").className="engineStatusBar "+engineCls;$("engineStateDetail").textContent=d.active_stage?"Working on "+d.active_stage.replaceAll("_"," ")+".":d.status==="failed"?"Main research is paused at "+(failed||"a validation gate").replaceAll("_"," ")+". Engineering/self-improvement can continue separately.":d.status==="complete"?"All scheduled research checkpoints completed.":"Controller is ready for the next scheduled pass.";
$("blocker").textContent=blocker?blocker.replaceAll("_"," ").toUpperCase():"NO CURRENT FAILURE";$("blockerDetail").textContent=blocker==="former_coverage"?"Former-constituent history is below the fixed 90% gate.":blocker==="overall_coverage"?"Historical-universe coverage is below the fixed 90% gate.":failed?"This stage failed closed; downstream work cannot be credited until resolved.":"No failed checkpoint is currently recorded.";
let nextIdx=d.active_stage?STAGES.indexOf(d.active_stage)+1:STAGES.findIndex(x=>!cp[x]||cp[x].status!=="complete");let next=nextIdx>=0&&nextIdx<STAGES.length?STAGES[nextIdx]:null;$("nextAction").textContent=next?next.replaceAll("_"," ").toUpperCase():"PIPELINE REVIEW";$("nextDetail").textContent=d.active_stage?"After the active stage completes, this is the next scheduled checkpoint.":"This is the next incomplete checkpoint in the fixed sequence.";
$("flow").innerHTML=GROUPS.map(([name,a,b])=>{let names=STAGES.slice(a,b),n=names.filter(x=>cp[x]&&cp[x].status==="complete").length,active=names.includes(d.active_stage),bad=names.some(x=>cp[x]&&cp[x].status==="failed");return '<div class="flowStep '+(active?"flowActive":bad?"flowBad":n===names.length?"flowDone":"")+'"><b>'+name+'</b><span>'+n+'/'+names.length+'</span></div>'}).join('<i>→</i>');$("activeStage").textContent=d.active_stage?d.active_stage.replaceAll("_"," ").toUpperCase():"—";$("stageTime").textContent=d.active_stage?fmt(elapsed):"—";$("eventCount").textContent=d.event_count??"—";
let live=$("liveBar");live.classList.toggle("moving",!!d.active_stage);live.style.width=d.active_stage?"100%":"0";
if(cv.overall!=null){$("coverage").textContent=cv.overall.toFixed(1)+"%";$("coverageBar").style.width=pct(cv.overall)+"%"}if(cv.former!=null){$("former").textContent=cv.former.toFixed(1)+"%";$("formerBar").style.width=pct(cv.former)+"%"}
let gate=cp.gatekeeper;$("gate").textContent=gate&&gate.status==="complete"?"CHECKED":"LOCKED";$("gateReason").textContent=gate&&gate.status==="complete"?"Gatekeeper stage completed":"Downstream work remains fail-closed";
let health=[...(d.output||"").matchAll(/B27B_SELF_REPAIR_CONTROL[^\n]*status=(\w+)/g)];$("providers").textContent=health.length?(health.at(-1)[1]==="HEALTHY"?"HEALTHY":"DEGRADED"):"—";
$("team").innerHTML=roles.map(([name,keys,icon])=>{let x=roleState(cp,keys,d.active_stage);return '<div class="agent '+(x.label==="ACTIVE"?"agentActive":"")+'"><b><i class="agentIcon '+name.toLowerCase().replaceAll(" ","-")+'">'+icon+'</i>'+name+'</b><span class="'+x.cls+'">● '+x.label+'</span><span class="muted">'+x.detail+'</span></div>'}).join("");
$("pipeline").innerHTML=STAGES.map((name,i)=>{let v=cp[name],[s,cls]=stageState(name,v,d.active_stage),detail=name===d.active_stage?fmt(elapsed):v?(v.duration_s!=null?fmt(v.duration_s)+" • attempt "+(v.attempt||"—"):"attempt "+(v.attempt||"—")):"not reached";return '<div class="stage '+(name===d.active_stage?"stageActive":"")+'"><b>'+(i+1)+'. '+name.replaceAll("_"," ")+'</b><span class="'+cls+'">'+s+'</span><span class="muted">'+detail+'</span></div>'}).join("");
let lines=(d.output||"").split("\n").filter(x=>/B27B_(FORMER|FETCH|SPECIALIST|RENAME|SECONDARY|REPAIR|UNIVERSE|GATE|OPTIMIZER|STAGE_(START|COMPLETE)|WATCHDOG)/.test(x));$("results").textContent=lines.slice(-40).join("\n")||"Waiting for research output…";$("lastEvent").textContent=d.last_event||"No event yet";$("updated").textContent="LIVE • "+new Date().toLocaleTimeString();
}catch(e){$("system").textContent="TELEMETRY OFFLINE";$("sub").textContent=e.message;$("updated").textContent="CONNECTION LOST"}}
tick();setInterval(tick,1000);

async function roomTick(){try{let r=await fetch("/api/research-room?ts="+Date.now(),{cache:"no-store"});if(!r.ok)return;let d=await r.json(),m=(d.history||[]).slice(-30);let cases=Object.values(d.cases||{}),tasks=(d.tasks||[]),act=d.activity||{};
$("agentActivity").innerHTML=Object.entries(act).map(([n,x])=>'<div class="opRow"><b>'+esc(n)+'</b><span>'+esc(x.status)+'</span><small>'+esc(x.current_mission)+' • '+Number(x.open_tasks||0)+' open • '+new Date((x.last_active||0)*1000).toLocaleTimeString()+'</small></div>').join("")||"No activity yet.";
let partial=cases.filter(x=>x.classification==="partial_history").length,missing=cases.filter(x=>x.classification==="former_unresolved"||x.classification==="missing_history").length;$("caseSummary").textContent=cases.length+" UNRESOLVED • "+partial+" PARTIAL • "+missing+" MISSING";
$("caseBoard").innerHTML=cases.slice(0,30).map(x=>'<button class="caseRow" data-symbol="'+esc(x.symbol)+'"><b>'+esc(x.symbol)+'</b><span>'+esc(x.owner)+' • '+esc(x.status)+'</span><small>'+esc(String(x.classification||"").replaceAll("_"," "))+' • '+Math.round((x.completeness||0)*100)+'% • '+esc(x.next_action)+'</small></button>').join("")||"No cases yet.";
$("caseBoard").querySelectorAll("[data-symbol]").forEach(el=>el.onclick=()=>{let x=cases.find(z=>z.symbol===el.dataset.symbol);if(!x)return;$("caseDetail").innerHTML='<b>'+esc(x.symbol)+' INVESTIGATION</b><p>Status: '+esc(x.status)+' • Owner: '+esc(x.owner)+' • Completeness: '+Math.round((x.completeness||0)*100)+'%</p><p>Expected/observed days: '+Number(x.expected_days||0)+' / '+Number(x.observed_days||0)+'</p><p>Next: '+esc(x.next_action)+'</p><pre>'+esc(JSON.stringify(x.missing||[],null,2))+'</pre>'});
$("taskBoard").innerHTML=tasks.slice(0,25).map(x=>'<div class="taskRow"><b>'+esc(x.to)+' ← '+esc(x.from)+'</b><span>'+esc(x.status)+'</span><small>'+esc(x.symbol)+' • '+esc(x.task)+'</small></div>').join("")||"No delegated tasks yet.";
let ev=(d.events||[]).slice(-15).reverse(),evidence=(d.evidence||[]).slice(-15).reverse();
$("eventBoard").innerHTML=ev.map(x=>'<div class="eventRow"><b>'+esc(x.type)+'</b><span>'+new Date((x.time||0)*1000).toLocaleTimeString()+'</span><small>'+(x.ticker?esc(x.ticker)+' • ':'')+esc(x.text)+'</small></div>').join("")||"No events yet.";
$("evidenceBoard").innerHTML=evidence.map(x=>'<div class="evidenceRow"><b>'+esc(x.ticker)+' • '+esc(String(x.claim||"").replaceAll("_"," "))+'</b><span>'+esc(x.gatekeeper_status)+'</span><small>'+esc(x.agent)+' • '+esc(x.source)+' • '+new Date((x.retrieved_at||0)*1000).toLocaleString()+'</small></div>').join("")||"No evidence yet.";
let hist=(d.coverage_history||[]).slice(-20);$("coverageTimeline").innerHTML=hist.length?hist.map(x=>'<div class="coveragePoint"><b>'+new Date((x.time||0)*1000).toLocaleString()+'</b><span>Overall '+(Number(x.coverage||0)*100).toFixed(2)+'%</span><span>Former '+(Number(x.former_coverage||0)*100).toFixed(2)+'%</span></div>').join(""):"No coverage measurements yet.";
$("discussion").innerHTML=m.length?m.map(x=>'<div class="message '+esc(String(x.kind||"finding"))+'"><b>'+esc(String(x.agent||"AGENT").toUpperCase())+' → '+esc(String(x.to||"TEAM").toUpperCase())+'</b><span>'+new Date((x.time||0)*1000).toLocaleTimeString([], {hour:"numeric",minute:"2-digit",second:"2-digit"})+' • '+Math.round((x.confidence||0)*100)+'% • '+esc(String(x.kind||"finding").toUpperCase())+'</span><p>'+esc(x.text||"")+'</p><small>EVIDENCE: '+esc(x.evidence||"—")+'</small></div>').join(""):"No agent conversation recorded yet.";}catch(e){}}
async function sendChat(){let agent=$("chatAgent").value,input=$("chatInput"),message=input.value.trim();if(!message)return;let log=$("chatLog");log.innerHTML+='<div class="you"><b>YOU</b><p>'+esc(message)+'</p></div>';input.value="";try{let r=await fetch("/api/agent-chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({agent:({"ARCHIVIST":"Former Tickers","ORACLE":"Corporate Actions","CIPHER":"Data Sources","PULSE":"Bottlenecks"}[agent]||agent),message})}),d=await r.json();log.innerHTML+='<div class="them"><b>'+agent.toUpperCase()+'</b><p>'+esc(d.reply||"No response.")+'</p></div>';log.scrollTop=log.scrollHeight}catch(e){log.innerHTML+='<div class="them"><b>SYSTEM</b><p>Agent channel unavailable.</p></div>'}}
$("chatSend").onclick=sendChat;$("chatInput").addEventListener("keydown",e=>{if(e.key==="Enter")sendChat()});roomTick();setInterval(roomTick,5000);

async function sendCommand(){let agent=$("cmdAgent").value,symbol=$("cmdSymbol").value.trim().toUpperCase(),task=$("cmdTask").value.trim();if(!symbol||!task)return;$("cmdResult").textContent="ASSIGNING…";try{let r=await fetch("/api/research-command",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({agent,symbol,task})});let d=await r.json();$("cmdResult").textContent=r.ok?"ASSIGNED • "+d.to+" • "+d.symbol+" • "+d.task:"COMMAND REJECTED";if(r.ok){$("cmdSymbol").value="";$("cmdTask").value="";roomTick()}}catch(e){$("cmdResult").textContent="COMMAND CHANNEL UNAVAILABLE"}}$("cmdSend").onclick=sendCommand;
